### ISSUE TITLE
Adding a list of strings to cleaner functions

### ISSUE THREAD

**Issue by MuhammadAlBarham** [TRoboto/Maha#46]
### What problem are you trying to solve?

Enhance the cleaners functions to take a list of strings as input if needed.

### Examples (if relevant)

```py
>>> from maha.cleaners.functions import remove
>>> text = "من اليوم سوف ينتقل صديقي منور من المدينة المنورة وعنوانه الجديد هو الرياض"
>>>remove(text, custom_expressions = [r"\bمن\b", r"\bعن\b")
'اليوم سوف ينتقل صديقي منور المدينة المنورة وعنوانه الجديد هو الرياض'

```

### Definition of Done

- It must adhere to the coding style used in the defined cleaner functions.
- The implementation should cover most use cases.
- Adding tests

**Comment by xaleel** [comment]
@TRoboto I believe the issue should also address the `:func:~maha.cleaners.functions.contains` as well. What do you think?

**Comment by TRoboto** [comment]
Yes, you can create a new PR for this.
